class LoremIpsum
  def self.generate(paragraphs = 2)
  @@lipsum ||= <<-DUMMYTEXT.split("\n").map { |e| "<p>#{e.strip}</p>" }
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam mollis, lectus vitae pharetra eleifend, augue risus suscipit felis, ac dapibus mi enim non sapien. Proin malesuada consequat orci. Nam tellus. Vestibulum fringilla justo quis justo. Fusce ac quam in lorem viverra sodales. Integer varius vestibulum magna. Pellentesque at ligula. Phasellus orci sapien, consectetuer in, tempus eu, condimentum vitae, nisl. Nulla tincidunt. Praesent dolor. Phasellus feugiat. Aenean est. Nullam varius.
    Curabitur odio risus, aliquet nec, elementum rhoncus, porta ac, mauris. In vitae odio vitae dui eleifend suscipit. Sed ac nisl. Pellentesque molestie elit id pede. Duis massa orci, congue vitae, porta ac, convallis vel, sem. Etiam quis dolor eu massa vestibulum accumsan. Integer leo. Nunc euismod tortor in quam. Sed elementum. Proin odio tortor, convallis molestie, ullamcorper in, tincidunt at, metus. Aliquam faucibus pulvinar turpis. Donec diam quam, rutrum quis, tristique ultrices, facilisis et, mauris. Pellentesque neque nibh, luctus vitae, ultrices nec, semper volutpat, erat. Maecenas pharetra leo ac leo. Sed luctus nonummy eros.
    Proin felis enim, feugiat ac, ultrices sit amet, consectetuer a, enim. Proin mollis nisl vitae metus. Fusce massa elit, ultrices vel, ornare et, cursus eu, lorem. Nulla sem nulla, ultrices non, venenatis id, vestibulum ac, augue. Phasellus tristique. Praesent feugiat luctus turpis. Nulla vitae leo nec nulla sodales tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ut orci. Nulla facilisi. Cras rhoncus erat vel felis. Donec dignissim ligula a dolor. Donec lectus.
    Nulla feugiat dignissim neque. Suspendisse et felis. Etiam mollis orci sit amet tortor. Vivamus nisl nunc, ornare sed, dictum vitae, bibendum fermentum, urna. Vestibulum accumsan, magna at interdum tempus, tellus mauris pellentesque dolor, eget mattis ligula sem laoreet libero. Aliquam vehicula, eros ut interdum varius, lectus ligula fringilla tortor, sit amet viverra felis nulla ut orci. Donec porta, neque in semper convallis, magna purus pharetra lorem, id porttitor orci metus vitae nunc. Mauris id leo. Aliquam tortor odio, faucibus eu, porta sollicitudin, lacinia ut, risus. Aliquam tincidunt nibh sit amet eros. Duis placerat felis vel odio. Nunc nisi massa, tempus porttitor, ornare vel, pellentesque blandit, enim. Aliquam a massa. Duis purus libero, cursus a, dapibus a, mollis ac, tellus. Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris eu libero ac lectus congue ornare. Duis posuere condimentum leo. Sed elit odio, pharetra vel, dictum a, hendrerit in, ante. Quisque vulputate, justo nec semper imperdiet, dolor nibh blandit erat, id facilisis nulla diam nec dui.
    Curabitur fringilla laoreet augue. Nulla nisi. Nullam dapibus ligula. Suspendisse potenti. Vestibulum sem. Donec fermentum, sem a mattis volutpat, quam elit congue nisi, eget tincidunt diam felis sed arcu. Sed at nulla ut tortor varius mattis. Donec rutrum. Morbi rhoncus, lectus eu venenatis feugiat, lorem lorem dictum purus, ac laoreet enim dui at nunc. Proin gravida enim eu odio. Pellentesque non velit. Curabitur et sem. Integer interdum dictum justo. Maecenas auctor lacinia arcu.
    Pellentesque arcu ligula, posuere non, accumsan et, scelerisque et, enim. Nullam sit amet dui. Sed nec nisi sed libero congue mattis. Morbi eget ipsum ut dolor elementum vehicula. Morbi mattis, elit id interdum tristique, dolor ipsum pharetra elit, in aliquet lorem est in magna. Nunc nisi metus, vestibulum vitae, lacinia non, semper a, velit. Nullam id lectus. Maecenas consectetuer. Nam vitae lacus eu libero tempor scelerisque. Aliquam convallis gravida turpis. Proin adipiscing nonummy elit.
    Quisque luctus. Nulla eros. Aenean lectus dui, consectetuer ut, semper ut, adipiscing cursus, velit. Donec imperdiet, urna id egestas lobortis, turpis lacus tristique justo, nec consectetuer purus augue in velit. Curabitur ante ligula, dapibus quis, ultrices et, dapibus nec, pede. Mauris eget massa non leo suscipit posuere. Duis sit amet augue. Suspendisse feugiat. In lacinia blandit velit. Integer arcu metus, commodo in, molestie sed, feugiat vitae, nibh. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In venenatis turpis vel magna. Phasellus iaculis nibh. Nullam auctor sollicitudin felis. Mauris eu tellus. Curabitur tristique urna sed purus. Donec gravida laoreet lorem.
    Vestibulum adipiscing, est at lacinia ultrices, diam enim pulvinar sapien, sit amet facilisis leo orci a lorem. Mauris eget diam eget lectus condimentum consequat. In rhoncus nulla. Nulla tempus tellus ut lacus. Ut malesuada lobortis diam. Etiam ut tortor. Nam mollis, est quis elementum elementum, pede neque consequat mauris, aliquet congue dui nulla sit amet nibh. Vestibulum sed nulla. Nulla risus mauris, porta in, laoreet a, molestie vestibulum, mi. Praesent id sapien. Aenean viverra hendrerit ligula.
    Sed lacinia. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ligula orci, interdum nec, pretium a, elementum vitae, elit. Nunc pharetra. Phasellus tincidunt. Donec orci. Vivamus porttitor accumsan tortor. Etiam ultrices, augue eu porttitor eleifend, ipsum orci malesuada neque, non mattis est sapien quis elit. Etiam sollicitudin porta tellus. Nulla in risus. Donec accumsan. Nulla tempor metus at neque. Sed faucibus fermentum lectus. Fusce tellus. Sed elit.
    Suspendisse non nibh. Aliquam ultricies ante vel lectus lacinia pretium. Proin id magna in lorem fringilla semper. Vestibulum in enim id massa volutpat gravida. Donec pharetra. Duis a quam. Proin ipsum. Etiam auctor, odio in euismod laoreet, tortor nibh aliquet ante, et dictum sapien nulla commodo nisi. Nullam imperdiet venenatis diam. Donec cursus diam ac ligula. Aliquam et sem.
  DUMMYTEXT
  
  (@@count ||= 0)
  @@count += 1
  srand 250 * @@count
  start = rand(@@lipsum.length - paragraphs)
  
  @@lipsum[start..start + paragraphs-1].join("\n  ")   
  end
end